### ISSUE TITLE
Note auto-complete search component

### ISSUE THREAD

**Issue by akaalias** [obsidianmd/obsidian-api#10]
Hi there!

I'm not sure if this exists or how I would find it but I would love to re-use the auto-complete search component that's currently in the "Daily Notes" settings: 

<img width="819" alt="Screenshot 2021-02-02 at 14 30 25" src="https://user-images.githubusercontent.com/111555/106607200-55c3e000-6563-11eb-91b7-cd3fe2435f01.png">

Any pointers before I start to re-invent this wheel? Thank you! :)

**Comment by lishid** [comment]
Hmm I don't think it's exposed at the moment but I can look into getting it ready for plugins in the next version or two.

**Comment by akaalias** [comment]
Yes, that would be super cool! It looks nice and works so well. I'd love to re-use it for the Start/End note search modal in my Journey plugin.

**Comment by akaalias** [comment]
I've made one myself for the time being. If you create a shared component let me know!

**Comment by lishid** [comment]
Currently working on wrapping up the next release, but I'll try to get it ready for the release after that.

**Comment by Vinzent03** [comment]
Am I missing something or is this feature still missing?

**Comment by ryanjamurphy** [comment]
> Am I missing something or is this feature still missing?

See e.g., https://github.com/obsidianmd/obsidian-api/blob/55946e5a6259a28c416d2d6e600a7964a86a01dd/obsidian.d.ts#L1066, @Vinzent03.

Workbench provides an example of one implementation: https://github.com/ryanjamurphy/workbench-obsidian/blob/4403d6ae0ba1f9f7b298bd9f333a00a2594dc83c/main.ts#L667

**Comment by Vinzent03** [comment]
But that's a modal and not as part of a text field in the settings pane?

**Comment by lishid** [comment]
That's correct, the auto-complete module hasn't been yet fully exposed. We're still working on the API to make it work across desktop and mobile.

**Comment by Vinzent03** [comment]
No problem. I am using a component from liam now.
