### ISSUE TITLE
Request: `Plugin.registerTimeout(id)`

### ISSUE THREAD

**Issue by kiavashp** [obsidianmd/obsidian-api#101]
As with `Plugin.registerInterval()`, if the plugin is unmounted before a timeout is set to fire, this method would unregister that timeout.

**Use Case:**
This of course prevents any short term timeout from firing after unload, but this is especially relevant for a plugin where I want to schedule some code to run at day change (midnight). So the timeout may be hours long, meaning there's a much higher chance for the plugin to be unloaded before the timeout is triggered.

**Comment by liamcain** [comment]
You can just use:

```ts
let timerId = window.setTimeout(() => { ... }, 3600);
plugin.register(() => clearTimeout(timerId));
```

**Comment by kiavashp** [comment]
Oh awesome! Thank you.
