### ISSUE TITLE
Bug: `Platform` specification is not complete

### ISSUE THREAD

**Issue by mnaoumov** [obsidianmd/obsidian-api#105]
In runtime I see that `Platform` constant has multiple useful properties that are missing from the specification, e.g. `Platform.isWin`

From the other hand, `Platform.isMacOS` is mentioned in the specification.

Such kinds of checks are required sometimes to filter out invalid filename characters. Windows' set of invalid characters are bigger than on other platforms.

**Comment by lishid** [comment]
Properties missing from the spec means it's not intended to be used by plugins - either we anticipate that it can change in the future, or we don't feel like it's robust enough to support it indefinitely.

I've decided to add some of the variables here for public use, but not all of it.
