### ISSUE TITLE
Request: Expose Codemirror loaded Language instances

### ISSUE THREAD

**Issue by mayurankv** [obsidianmd/obsidian-api#117]
## Request

It would be useful to expose the loaded Language instances (or LanguageSupport) instances that obsidian has loaded so that plugins could add codemirror syntax highlighting in editing mode.

## Motivation

This would expose further functionality to allow for plugins to have a more in-depth ability to deal with writing code (i.e. adding autocompletion, bracket matching or other language features).
Also it would mean that a plugin reliant on the '@codemirror/lang-data' module wouldn't have to load a new instance of a language (that obsidian has already loaded) to use syntax highlighting.

Thank you for your consideration!

**Comment by mayurankv** [comment]
In addition, it would be great to expose the Highlighter that Obsidian uses (even if the languages themselves are not exposed) so plugins would have highlighting consistent with obsidian itself.

**Comment by lishid** [comment]
Language parsing support currently relies on the old CodeMirror 5 system, you should be able to hook up to it using the global CodeMirror object from a plugin.

**Comment by lishid** [comment]
Also issues in this repo is only for bugs with the API - if you have feature requests for the API, or questions, please post in our discord server's #plugin-dev channel, or the forum at https://forum.obsidian.md/ instead.

**Comment by mayurankv** [comment]
Thank you for your help, that's answered everything I wanted to know! I managed to get syntax highlighting done within the plugin.

Apologies, I thought I saw another request issue but I'll default to the forum next time.

Out of curiosity, is Obsidian likely to transition to the codemirror 6 Language style parsing (any time soon I guess) or not really?

**Comment by lishid** [comment]
> Out of curiosity, is Obsidian likely to transition to the codemirror 6 Language style parsing (any time soon I guess) or not really?

Unlikely for the time being. Unfortunately a lot of editor-related functionalities ended up depending on the stream parser, including Live Preview and other token based functionality like context menu actions. A switch in the syntax parser would likely mean a major rewrite of the editor integration which isn't something we can commit to right now.
