### ISSUE TITLE
Bug: As of Obsidian 1.4.0, FrontMatterCache no longer has position

### ISSUE THREAD

**Issue by isaaclyman** [obsidianmd/obsidian-api#122]
**Steps to reproduce:**
- Use `const metadata = App.metadataCache.getFileCache(file)` to get file metadata
- Refer to `metadata.frontmatter`, which has the type `FrontMatterCache`
- `FrontMatterCache` inherits from `CacheItem`, which has a non-nullable `position` field of type `Pos`
- However, `metadata.frontmatter` does not have a `position` field

https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L1518

This breaks my plugin, Novel Word Count, which checks for null on `frontmatter` but not on `frontmatter.position`.

EDIT: I was firefighting because the plugin crashed for my users, but now I see in the release notes that FrontMatterCache isn't supposed to inherit from CacheItem anymore. Is there another way to get the start and end position of frontmatter? My users don't like frontmatter being included in their word and page count.

**Comment by isaaclyman** [comment]
Awesome, thank you for the reply. I see why that's necessary. Very glad to see there's a painless way to update.

**Comment by lishid** [comment]
You'll likely want to use a fallback for older versions of obsidian for a while `cache.frontmatterPosition || cache.frontmatter?.position`

**Comment by isaaclyman** [comment]
Yeah, that's what I ended up doing. :+1: thanks!
