### ISSUE TITLE
Bug: app.vault.getAbstractFileByPath always return null

### ISSUE THREAD

**Issue by swhoro** [obsidianmd/obsidian-api#123]
![image](https://github.com/obsidianmd/obsidian-api/assets/34229589/dffc62c3-acdb-46d1-97fb-ba99dba03e8b)

As the image show, `app.vault.getAbstractFileByPath` can only get root ("/") TAbstractFile, but cannot get any other sub folders or files

The bug can be reproduced both in dev console and in dataviewjs block

**Comment by joethei** [comment]
This is to be expected, paths in Obsidian don't start with a slash.
(The root folder `/` is a special case)

**Comment by swhoro** [comment]
> This is to be expected, paths in Obsidian don't start with a slash.
> (The root folder `/` is a special case)
> 

thank you
