### ISSUE TITLE
[Plugin] Add Callout component API like `ButtonComponent`, etc

### ISSUE THREAD

**Issue by LBF38** [obsidianmd/obsidian-api#125]
Hello the Obsidian team !

Is it possible that you make public the Callout Components to be easier to create Callouts inside plugin ?
It could be similar to `ButtonComponent` or other ones such as `Setting`.

Thanks !

**Comment by lishid** [comment]
Thanks for the input! This repo is only used for bugs with the API. Feature requests should go on the forum in the [Developer & API section](https://forum.obsidian.md/c/developers-api/14). Thank you!
