### ISSUE TITLE
Bug: Focusing issues with webviews in multiple windows

### ISSUE THREAD

**Issue by pjeby** [obsidianmd/obsidian-api#130]
This applies to anything that uses webviews, not just canvases, but here's a canvas repro:

**Steps to reproduce:**
- Open a canvas containing a webview in two different windows
- Click to obtain keyboard focus in each webview, one after the other
- Now alt-tab between them (Windows 10; untested on any other platforms)
- Expected: is-focused class should reflect the active window
- Actual: no updates to is-focused class for either window (both believe they are unfocused).

I'm working around it with this:

```typescript
                const {win, doc} = this.webview;
                win.electronWindow?.on("blur", doBlur);
                win.electronWindow?.on("focus", doFocus);
                return () => {
                    win.electronWindow?.off("blur", doBlur);
                    win.electronWindow?.off("focus", doFocus);
                }
                function doBlur() { doc.body.removeClass("is-focused"); }
                function doFocus() { doc.body.addClass("is-focused"); }
```

I'm guessing that the current blur/focus detection is targeting the document instead of the electron window.  I also haven't yet confirmed whether activeWindow and activeDocument are tracking correctly here either, but I would guess they have the same issue, likely it would show up if you alt-tab to a window with an active webview, dialogs might open in a different window, etc.  (And I had something like that happen at one point, need to work out a repro though.)

It looks like the window-level focus/blur detection (for the rootsplit and popouts) could maybe just switch to using the electron window since they're conditional on Platform.isDesktopApp anyway.  (I think, though, that the document focus stuff might also need some work since focusing into a web view appears to lose `is-focused` on the current window as well.)

**Comment by lishid** [comment]
I have a patch that addresses this issue in the upcoming release, thanks!
