### ISSUE TITLE
Bug: Copy from IDE and Paste in Obsidian leads to an extra line

### ISSUE THREAD

**Issue by LordMoMA** [obsidianmd/obsidian-api#131]
**Steps to reproduce:**
-
helper plugin and available solution online from contributor of Obsidian community did not work properly, please solve this issue, really annoying.

**Comment by liamcain** [comment]
Hi, this is the repo for the Obsidian API, not Obsidian itself.

If you have any feedback about Obsidian, please go to https://forum.obsidian.md/ instead, thanks!
