### ISSUE TITLE
Bug: custom SVG call out icon display nothing.

### ISSUE THREAD

**Issue by tim-hub** [obsidianmd/obsidian-api#132]
**Steps to reproduce:**
-

1. Follow this documentation, https://help.obsidian.md/Editing+and+formatting/Callouts#Customize+callouts
2. set up the call out icon to a custom svg, for example

```
--callout-icon: '<svg><path d="M96 77.3c0-7.3 5.9-13.3 13.3-13.3c3.5 0 6.9 1.4 9.4 3.9l14.9 14.9C130 91.8 128 101.7 128 112c0 19.9 7.2 38 19.2 52c-5.3 9.2-4 21.1 3.8 29c9.4 9.4 24.6 9.4 33.9 0L289 89c9.4-9.4 9.4-24.6 0-33.9c-7.9-7.9-19.8-9.1-29-3.8C246 39.2 227.9 32 208 32c-10.3 0-20.2 2-29.2 5.5L163.9 22.6C149.4 8.1 129.7 0 109.3 0C66.6 0 32 34.6 32 77.3V256c-17.7 0-32 14.3-32 32s14.3 32 32 32H480c17.7 0 32-14.3 32-32s-14.3-32-32-32H96V77.3zM32 352v16c0 28.4 12.4 54 32 71.6V480c0 17.7 14.3 32 32 32s32-14.3 32-32V464H384v16c0 17.7 14.3 32 32 32s32-14.3 32-32V439.6c19.6-17.6 32-43.1 32-71.6V352H32z"/></svg>';
```

## Issue

- Nothing show up now.

![image](https://github.com/obsidianmd/obsidian-api/assets/2884320/587b477f-5cfe-46fa-b8fa-d91b7262aec7)
![image](https://github.com/obsidianmd/obsidian-api/assets/2884320/50998f80-2850-4155-8cf5-d3d761354000)

## Expect

- custom icon got rendered
![image](https://github.com/obsidianmd/obsidian-api/assets/2884320/97ce983e-80a5-4499-a336-4f5a2d74daf3)

**Comment by lishid** [comment]
The bug seems to be with parsing single quotes for now. I have a fix for this, but it will only be applied in the next release.
In the meantime, you can remove the single quote, or use double quotes instead.
