### ISSUE TITLE
Can I make API feature requests here?

### ISSUE THREAD

**Issue by Oneechan69** [obsidianmd/obsidian-api#141]
I'm not sure since the bug template is the only issue template, but I saw a few feature request issues here as well.

**Comment by lishid** [comment]
Your best bet is to either discuss your needs in the discord server `#plugin-dev` (maybe someone can help you find a workaround), or write a post on the forum developer & API section: https://forum.obsidian.md/c/developers-api/14

**Comment by Oneechan69** [comment]
@lishid Then would about these? https://github.com/obsidianmd/obsidian-api/labels/feature-request

**Comment by lishid** [comment]
I believe those are old requests made before it was clear that feature requests should go to the forum.

**Comment by Oneechan69** [comment]
@lishid Which sub-forum though? on Feature Requests, or on Developers & API?

**Comment by lishid** [comment]
From my previous comment:
> write a post on the forum developer & API section: https://forum.obsidian.md/c/developers-api/14
