### ISSUE TITLE
Bug: the normalizePath function Unable to completely filter illegal characters

### ISSUE THREAD

**Issue by flyer1b** [obsidianmd/obsidian-api#146]
**Steps to reproduce:**
- when I write the article with the title,it notice the error.
- <img width="316" alt="image" src="https://github.com/obsidianmd/obsidian-api/assets/11568049/b30b912c-2339-49ac-a583-f057718cb95e">
- key code:
<img width="772" alt="image" src="https://github.com/obsidianmd/obsidian-api/assets/11568049/04e7c8fc-2ff6-466d-8648-97c7b93a14c2">

**Comment by lishid** [comment]
normalizePath isn't meant to strip or clean the path itself; its purpose is to normalize the path components to remove duplicate slashes and convert all slashes to forward slashes. You should strip/clean the filenames before sending it through.
