### ISSUE TITLE
Update docs to include list of all supported events

### ISSUE THREAD

**Issue by toddmedema** [obsidianmd/obsidian-api#15]
I'm trying to figure out how to do something not mentioned in the sample plugin https://github.com/obsidianmd/obsidian-sample-plugin

Specifically, I want to listen for changes to the active markdown file's text / contents.

But, I don't even know if this is possible, because there's no list of what events I can listen to :)

**Comment by lishid** [comment]
There are Vault and MetadataCache events you can listen to documented in https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts

**Comment by toddmedema** [comment]
Thanks, that works for now!
