### ISSUE TITLE
Bug: requestURL when body is arraybinary or formdata, I try to transform formdata to array put it in body of request, but failed.

### ISSUE THREAD

**Issue by ai-chen2050** [obsidianmd/obsidian-api#150]
**Steps to reproduce:**
## First 
- Here is some [reproduction info](https://forum.obsidian.md/t/holo-how-to-add-a-png-image-or-file-to-formdata-in-obsidian-like-below-this-help/73420).

## Second

I don't know why the server ip is not same when I use obsidian reqestUrl and python command line, here are some I debug info ( print info and wireshark info), it related the formdata and upload a image file to server (and [material/add_material?](https://developers.weixin.qq.com/doc/offiaccount/en/Asset_Management/Adding_Permanent_Assets.html)  interface),  I handle my self in the obsidian, but I have been triple checked, and sure, they are same binary body in two method.

first, I try my best to make the body the same in two methods. but IP is not same in two methods. It's becouse DNS ? ?  I don't know why.

1. python shell command line,   pass
```py
requests.request("POST", url, headers=headers, data=payload, files=files)
```
![python ok](https://media.discordapp.net/attachments/840286264964022302/1188500806887034930/image.png?ex=659ac0a1&is=65884ba1&hm=a184bc2422a994d40d49425fd628af7f20a53479705e74061927fcf1db463f1b&=&format=webp&quality=lossless&width=1708&height=252)

2. obsidian requestUrl,  fail
![ob fail](https://media.discordapp.net/attachments/840286264964022302/1188500807201603624/image.png?ex=659ac0a1&is=65884ba1&hm=2d05669dfedb2e53412e2ec9cf9f8dc0ec2279cba360ab2647d56f8ec784de15&=&format=webp&quality=lossless&width=1708&height=264)

3. python wireshark,  true data
![py](https://media.discordapp.net/attachments/840286264964022302/1188500807503589476/152991703429924_.pic_.jpg?ex=659ac0a1&is=65884ba1&hm=276ff86a9f83492c7ca7975d00424e051e9d3451252d855adcbd8a44fa4b6cb7&=&format=webp&width=1708&height=368)

4. obsidian requestUrl wireshark, not see true data
![ob](https://media.discordapp.net/attachments/840286264964022302/1188500807910445227/153011703430035_.pic_.jpg?ex=659ac0a1&is=65884ba1&hm=419c78f3716e127e74ad4e28c3eaa8c2f5042e37dac0e70286b8fdc12dd10cbb&=&format=webp&width=1708&height=276)

## Three
I have try [python code](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/master/tests/fromDataReq.py) and [nodejs](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/master/tests/nativeFetch.js) request the interface upload a file all are oks.  But using requestUrl in obsidian fail, some [sourcecode](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/9fdecb96966eaafdd6cbac716ffa5da3fb8d4b2b/src/api.ts#L92) in here.

**Comment by lishid** [comment]
`requestUrl` does not support `FormData`. You must supply the full http request body either as a string or as an `ArrayBuffer`. Unfortunately this does make it quite a bit tedious to work with multipart form data.

**Comment by ai-chen2050** [comment]
Thx, I fix this problem, just replace body: post_typedArray using body: post_typedArray.buffer.

**Comment by maxtimbo** [comment]
Is there a possibility of this getting patched to accept multipart form data?

**Comment by ai-chen2050** [comment]
> Is there a possibility of this getting patched to accept multipart form data?

You can simulate a multipart form data request, as follows. 
- go to my project and give it a star, thx
- then click here to watch some [details](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/81f9f4f8b5edaa43605209dd8d2c8476a0f72958/src/api.ts#L182) about how to handle using form-data

**Comment by maxtimbo** [comment]
> then click here to watch some details about how to handle using form-data

Yep, I've looked over your code a bunch of times. It's the only reference I've been able to find. It has not worked for my use case. See the code and my attempts [here](https://github.com/maxtimbo/discourse-sync/blob/main/src/main.ts)

**Comment by ai-chen2050** [comment]
Sorry to hear about that, You can try other ways more. I am working now, so I may check out your code details when I am not busy.
