### ISSUE TITLE
Version 1.5.1 is not published on npmjs

### ISSUE THREAD

**Issue by MatiasVerdier** [obsidianmd/obsidian-api#153]
Currently 1.4.11 is the latest version on [npm](https://www.npmjs.com/package/obsidian/v/1.4.11)

This could be the cause of the following error I'm having while developing a plugin

![image](https://github.com/obsidianmd/obsidian-api/assets/5176883/82a8001e-1764-414f-aa8e-f7ff085e6bc0)

For example `obsidian-local-rest-api` build is failing because of this

https://github.com/coddingtonbear/obsidian-local-rest-api/actions/runs/7601968814/job/20701963500

## Temporary solution
Changing the version in the `package.json` to `1.4.11` instead of `latest`

**Comment by lishid** [comment]
Just pushed 1.5.7 to npm!
