### ISSUE TITLE
Bug: Lack of upstream version of mermaid limits the diagram which can be used

### ISSUE THREAD

**Issue by nuschpl** [obsidianmd/obsidian-api#159]
**Steps to reproduce:**
- Install recent version of Obsidian
- Enter the following markdown to get representation of some packet(like TCP/IP packet):
````
```mermaid
packet-beta
0-15: "field1"
16-31: "field2"
```
````
- Get the result 'No diagram type detected matching given configuration for text: packet-beta'
- Enter same code on some online mermaid generator - get the diagram

The root cause is lack of upstream version of mermaid which contains merged this pull request https://github.com/mermaid-js/mermaid/pull/4839/commits

**Comment by joethei** [comment]
This is not a bug, we haven't upgraded mermaid to that version yet.
Also, this is the repository for our API, not for the app itself.

Feature requests are collected on the forum: https://forum.obsidian.md/c/feature-requests/8
