### ISSUE TITLE
Mechanism to detect whether the plugin is running on Mobile or Desktop

### ISSUE THREAD

**Issue by renehernandez** [obsidianmd/obsidian-api#16]
As of now there is no sanctioned way of detecting inside a plugin code that it is running in the mobile app vs the desktop. 

This comes handy for the following reasons:
- Usage of a feature that is only available on Desktop or Mobile
- Change design and visuals based on whether is running on Mobile or Desktop.

As of now, I am aware of the possibility of using `app.isMobile`, but that involves having to extend the `typings` declaration, plus the fact that I am using an undocumented API that could be changed/removed in the future

**Comment by Vinzent03** [comment]
Is added by the new insider [release](https://forum.obsidian.md/t/obsidian-release-v0-12-2-insider-build/17602) and already documented https://github.com/obsidianmd/obsidian-api/commit/48bd2b91f66aa7d3768629be48c52e5351ec6696

**Comment by lishid** [comment]
For whoever still reading, this has been available for some time and the docs can be found at:

```ts
export const Platform {
```

https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L2067
