### ISSUE TITLE
Bug: Link is duplicated in frontmatter cache when the link is in a footnote

### ISSUE THREAD

**Issue by stroiman** [obsidianmd/obsidian-api#166]
**Steps to reproduce:**
-
In a sandbox vault, create the following note:

```markdown
What if there is a link in the footnote[^1].

[^1]: Here is [[The link]]
```

Run this in the console:

```javascript
this.app.metadataCache.getFileCache(app.workspace.getActiveFile()).links
```

The link is shown twice, with the same position

<img width="538" alt="image" src="https://github.com/obsidianmd/obsidian-api/assets/237227/3bc6b41a-dbda-4689-8ad7-8e08c43504ca">

Move the link out of the footnote, and the metadata only has one link as expected

**Comment by lishid** [comment]
Thanks, I have a fix that will be included in a future release.
