### ISSUE TITLE
`CHANGELOG.md` not updated for latest version

### ISSUE THREAD

**Issue by timrogers** [obsidianmd/obsidian-api#167]
Hi there! 👋

Thanks for creating the Obsidian API - it's so great to be able to create plugins for my favourite note-taking tool 🥳 

I can see that a new version of the `obsidian` npm package was released earlier this week, [v1.6.6](https://www.npmjs.com/package/obsidian). The [`CHANGELOG.md` file](https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md) has not been updated, which makes it hard to know what has changed or if it is safe to [update my plugin's dependency](https://github.com/timrogers/obsidian-share-as-gist/pull/607).

Would you be update to update the `CHANGELOG.md`?

Thanks! ❤

**Comment by liamcain** [comment]
For clarity, we have added the following to the top of the changelog file:

> This CHANGELOG details any breaking changes to the API or new additions that require additional context. The versions listed below correspond to the versions of the Obsidian app. There may not be a corresponding package version for the version listed below.
