### ISSUE TITLE
Version 1.5.11 changelog

### ISSUE THREAD

**Issue by mnaoumov** [obsidianmd/obsidian-api#169]
`CHANGELOG.md` mentions version `1.5.11` but based on the history of `package.json`, this version was never released

**Comment by lishid** [comment]
Yeah the changelog is manually written of the summary of changes in the app (with respect to the API) and the releases here are auto generated typings from the main app code which don't happen at the same pace. If the changelog mentions a version then it likely means this was added in the app version. The API typings sometimes don't get updated until we send everything to public.

**Comment by mnaoumov** [comment]
@lishid thanks for the explanation. Those questions wouldn't be asked if #168 is done

**Comment by liamcain** [comment]
The changelog.md file has been updated to clarify this distinction.
