### ISSUE TITLE
FR: Replace `any` with `unknown`

### ISSUE THREAD

**Issue by mnaoumov** [obsidianmd/obsidian-api#173]
API has tons of `any` type arguments.

While it is a valid TypeScript, it doesn't force the strictest TypeScript rules such as [no-explicit-any](https://typescript-eslint.io/rules/no-explicit-any/).

I think replacing `any` with `unknown` makes typings more reliable.

**Comment by lishid** [comment]
I can look into it. I think some of them might be breaking changes (or at least cause builds to fail) for plugins so I would be hesitant to replace all of them. There's also quite a lot and we have to go through it in code since it's generated, so this might take a while.

**Comment by lishid** [comment]
But thanks for the request, it's good to know that `unknown` is a better alternative to `any` these days, I wasn't aware of the difference until I did some reading!

**Comment by mnaoumov** [comment]
I agree it might be a breaking change, but, in my opinion,

1. It totally worth it as it improves the code quality
2. The fixes for the plugin developers required are relatively easy and we can document them in the migration guide.
3. You can totally involve me at any stage for testing and writing migration documentation, etc, if you see any use of my skills.

**Comment by liamcain** [comment]
We'll be making some improvements for the next public release.
