### ISSUE TITLE
`leftSplit`, `rightSplit`, and `rootSplit` types are not defined?

### ISSUE THREAD

**Issue by ryanpcmcquen** [obsidianmd/obsidian-api#20]
<img width="841" alt="Screen Shot 2021-06-06 at 2 56 30 PM" src="https://user-images.githubusercontent.com/772937/120941393-6766f100-c6d7-11eb-95cc-4d2b68f48578.png">
I see that these live on `Workspace`, but they don't seem to be picked up as I would expect. Also, I don't see `collapse()`, `expand()`, or `collapsed` anywhere in the type definitions.

**Comment by lishid** [comment]
`Workspace` is the class definition - you're looking for the instance `app.workspace`.

`collapsed` isn't exposed yet.
