### ISSUE TITLE
Event when block is loaded back into DOM?

### ISSUE THREAD

**Issue by valentine195** [obsidianmd/obsidian-api#24]
As the title says, is there an event for when an element is loaded back into a note's DOM? I looked through the API, but didn't see one.

Use case:

My plugin uses LeafletJS, which has several functions related to the size of the containing element. If the map block is placed at the bottom of a long note, the containing element will not have a size, resulting in issues related to zooming and panning the map.

If I can detect when the element is added back in, I can tell the map to recalculate its scaling to the new container size. I built a workaround using a `MutationObserver` that disconnects itself once the map container has a size (only need to do it once), but I figured a native solution would be better.

**Comment by lishid** [comment]
There isn't, but the container element is passed through the context object, and you can use its `clientWidth` to figure out how much space you have.

Would this solve your use case?

**Comment by valentine195** [comment]
Unfortunately not - I actually know the container size in the plugin (it has to be explicitly set for Leaflet), but Leaflet looks at the clientWidth of its container element internally to get its scaling factors.

**Comment by valentine195** [comment]
Would you prefer I do that over using a MutationObserver observing the context container, then?

Easy enough, if so. 

Either way, thanks for the suggestion!

**Comment by lishid** [comment]
I think both solutions are fine - just make sure you write some comments on the various hacks you employ on why they're necessary and what they do.

**Comment by pjeby** [comment]
@valentine195: Is this now resolved with the addition of `onNodeInserted()`?  It sounds like that provides the originally requested feature, i.e. a callback for when an element is re-added to the DOM.

**Comment by valentine195** [comment]
Yes, thanks!
