### ISSUE TITLE
Obsidian triggers "create" event for each note when booting?

### ISSUE THREAD

**Issue by Creling** [obsidianmd/obsidian-api#25]
![image](https://user-images.githubusercontent.com/43109504/128152131-3c39f291-5623-4a0a-b21d-b88b73c6be82.png)
 
Is it a bug or a feature? What should I do if I only want to catch the _create_ event triggered after booting?

**Comment by Vinzent03** [comment]
Wrap your event registration in `app.workspace.onLayoutReady()`

**Comment by Creling** [comment]
> Wrap your event registration in `app.workspace.onLayoutReady()`

It works, thx. :)
