### ISSUE TITLE
Preserve CJK characters in `normalizePath` function

### ISSUE THREAD

**Issue by tadeoos** [obsidianmd/obsidian-api#26]
Hey,

One of our plugin's users mentioned this here: https://github.com/readwiseio/obsidian-readwise/issues/3

They are suggesting using a custom sanitization function instead, but ideally, I'd like to still use Obsidian's own `normalizePath` function and satisfy the user's needs. 

Is there a specific reason you're normalizing those characters as well as slashes etc.? 
Could we perhaps control this behavior with a param?

If you don't think this is a good idea at all — any chance for a suggestion on how to best mitigate this?

Thanks a lot for the Obsidian app and keep up the good work!

**Comment by tadeoos** [comment]
Guys, I'm terribly sorry this is on our end! Closing

**Comment by lishid** [comment]
No problem! I thought I'd reply that `normalizePath` shouldn't romanicize CJK characters since it's used internally in Obsidian throughout to interact with the file system so there's no way that behavior could have happened without us knowing 😉.

Either way, glad you have it figured out!
