### ISSUE TITLE
Bug: `origin` param in `Editor.replaceRange`/`replaceSelection` not working

### ISSUE THREAD

**Issue by aidenlx** [obsidianmd/obsidian-api#28]
https://github.com/obsidianmd/obsidian-api/blob/5af3ef982328a2dd0a2f5242f3c74e2f45e07896/obsidian.d.ts#L733-L736

Seems that in the source code, the last param (`origin`) is never read and only range and replacement params get passed to CodeMirror instance, so when batch editing document, the change histories can not [be merged as expected](https://codemirror.net/doc/manual.html#selection_origin). 

IMO, since CodeMirror 6 and 5 have distinct implementation on history, I think an helper function can be provided to allow batch editing, similar to vscode, which use [`WorkspaceEdit`](https://vshaxe.github.io/vscode-extern/vscode/WorkspaceEdit.html) to keep track of batch changes.

**Comment by lishid** [comment]
The origin parameter controls something internal to CodeMirror and CM5 vs 6 use different sets of strings, so it's only hooked up for specific purposes; I wouldn't recommend using it for batching (especially not CM6).

> I think an helper function can be provided to allow batch editing

That's the purpose of this function:
https://github.com/obsidianmd/obsidian-api/blob/5af3ef982328a2dd0a2f5242f3c74e2f45e07896/obsidian.d.ts#L771

**Comment by aidenlx** [comment]
Thanks! I'll give it a try. 

> I wouldn't recommend using it for batching (especially not CM6).

Meanwhile, can `origin` param mapped to CM6? If not, I think the `origin` param could be removed from declaration to avoid confusion.

**Comment by lishid** [comment]
I'll see what I can do.

**Comment by lishid** [comment]
It can be mapped to "userEvent" of a transaction, which is what I'll do.
