### ISSUE TITLE
Document Keymap.isModifier, since it's the right way to check for the mod key on events

### ISSUE THREAD

**Issue by pjeby** [obsidianmd/obsidian-api#29]
I've been trying to encourage plugin developers to use `event.button == 1 || Keymap.isModifier(event, "Mod")` as the Obsidian standard way to detect "a click that should open in a new pane", but it turns out that Keymap isn't actually listed in the API despite being exported.  (See e.g. the last paragraph of [this comment](https://github.com/alexobenauer/Cross-reference-Navigation-for-Obsidian/issues/3#issuecomment-925143877), and subsequent disussion re: Keymap.)

The other Keymap statics are occasionally useful, too, but this one seems particularly important for writing plugins that work consistently across platforms the way Obsidian does.

**Comment by lishid** [comment]
Omg I forgot to mark `Kepmap` as `@public`... Will do that now!

**Comment by lishid** [comment]
I even added a `isModEvent` that's now the standard way to check for `button === 1 || isModifier("Mod")` thinking it went through lol...

**Comment by pjeby** [comment]
Closing since both are documented now.
