### ISSUE TITLE
Icon Gallery

### ISSUE THREAD

**Issue by testgoofy** [obsidianmd/obsidian-api#3]
Is it possible to add a Wiki - page with all existing icons for the `addRibbonIcon()` - method?
Or at least to explain how to use the `addIcon()` - method

**Comment by denolehov** [comment]
Licat provided this list of icons on discord:
```
'logo-crystal', 'create-new', 'trash', 'search', 'right-triangle', 'document', 'folder', 'pencil', 'left-arrow', 'right-arrow', 'three-horizontal-bars', 'dot-network', 'audio-file', 'image-file', 'pdf-file', 'gear', 'documents', 'blocks', 'go-to-file', 'presentation', 'cross-in-box', 'microphone', 'microphone-filled', 'two-columns', 'link', 'popup-open', 'checkmark', 'hashtag', 'left-arrow-with-tail', 'right-arrow-with-tail', 'lines-of-text', 'vertical-three-dots', 'pin', 'magnifying-glass', 'info', 'horizontal-split', 'vertical-split', 'calendar-with-checkmark', 'sheets-in-box', 'up-and-down-arrows', 'broken-link', 'cross', 'any-key', 'reset', 'star', 'crossed-star', 'dice', 'filled-pin', 'enter', 'help', 'vault', 'open-vault', 'paper-plane', 'bullet-list', 'uppercase-lowercase-a', 'star-list', 'expand-vertically', 'languages', 'switch', 'pane-layout', 'install'
```

I am not sure if there is some "central page" with icons reference, perhaps on forums?

**Comment by testgoofy** [comment]
This helps, thanks

**Comment by v-i-s-h** [comment]
I would also like to know where I can search up the most up-to-date list of icons. I could not understand what/who is `licat`?

**Comment by ryanjamurphy** [comment]
@v-i-s-h The full list is above, in https://github.com/obsidianmd/obsidian-api/issues/3#issuecomment-724665569. Licat is @lishid, one of Obsidian's developers.

**Comment by doitian** [comment]
👍 https://github.com/obsidianmd/obsidian-api/issues/3#issuecomment-724665569

I created a page to preview the icons using dataview

<details>
<summary>Icon Gallery.md</summary>

~~~markdown
> [!info]- Icons
> - logo-crystal
> - create-new
> - trash
> - search
> - right-triangle
> - document
> - folder
> - pencil
> - left-arrow
> - right-arrow
> - three-horizontal-bars
> - dot-network
> - audio-file
> - image-file
> - pdf-file
> - gear
> - documents
> - blocks
> - go-to-file
> - presentation
> - cross-in-box
> - microphone
> - microphone-filled
> - two-columns
> - link
> - popup-open
> - checkmark
> - hashtag
> - left-arrow-with-tail
> - right-arrow-with-tail
> - lines-of-text
> - vertical-three-dots
> - pin
> - magnifying-glass
> - info
> - horizontal-split
> - vertical-split
> - calendar-with-checkmark
> - sheets-in-box
> - up-and-down-arrows
> - broken-link
> - cross
> - any-key
> - reset
> - star
> - crossed-star
> - dice
> - filled-pin
> - enter
> - help
> - vault
> - open-vault
> - paper-plane
> - bullet-list
> - uppercase-lowercase-a
> - star-list
> - expand-vertically
> - languages
> - switch
> - pane-layout
> - install

```dataviewjs
const icons = dv.current().file.lists.map((l) => l.text);

await dv.table(
  ["Icon", "Name"],
  icons.map((l) => ["", l])
);

dv.container.querySelectorAll("tbody tr").forEach((tr, index) => {
  const td = tr.querySelector("td");
  obsidian.setIcon(td, icons[index], 16);
});
```
~~~

</details>

The icon `two-columns` no longer exists.

**Comment by Smitty010** [comment]
This is helpful, but I'm not sure it's complete.  For example, I think "volume-1" and "volume-2" are missing

**Comment by doitian** [comment]
> This is helpful, but I'm not sure it's complete. For example, I think "volume-1" and "volume-2" are missing

Obsidian also supports icons from https://lucide.dev/ . Since Lucide keeps adding new icons, some are not available in Obsidian.

**Comment by Smitty010** [comment]
Thanks

**Comment by ljavuras** [comment]
I wrote a dataview script to list all icons available to `setIcon()`:
![image](https://github.com/user-attachments/assets/502b141d-6fab-4c8c-af89-4dc5c390fd02)
Gist [here](https://gist.github.com/ljavuras/28095f04113fda73f7dc4efcc776b94f)
