### ISSUE TITLE
Perform modifications at save

### ISSUE THREAD

**Issue by endorama** [obsidianmd/obsidian-api#32]
I've seen multiple plugins that performs action "on save", but I've not been able to find a proper API for it.

What I've seen being done in the wild so far is an override for the `editor:save-file` command callback, but it feels sub-optimal.  
Are there any plans to make this easier, adding a dedicated event?

**Comment by lishid** [comment]
There isn't such an API and I don't currently have any intentions of providing one.

I understand there are valid use cases for it, but it would be a dangerous hook to provide as plugins can easily cause corruption or data loss if the event is mishandled.

It is also unclear what should qualify as an "on save" event - does the plugin want to handle saves from the markdown editor, or all file saves on a file system level? Does batch updating internal links on rename qualify as a "save"? Does Obsidian Sync's write to disk qualify as a "save"?

While you can't intercept file changes, you can detect them using Vault's `create` and `modify` events. Make sure you debounce your event handlers properly as sometimes these events can be fired in rapid successions on multiple files.
