### ISSUE TITLE
is it possible to get header, status code, binary data in request()?

### ISSUE THREAD

**Issue by fyears** [obsidianmd/obsidian-api#35]
Hi,

I am building a plugin that requires http digest auth that requires reading response headers and status code.

Currently, the request() is the only way to bypass the annoying cors problem on obsidian mobile. But it seems that the function only returns the body as string and omits other information.

1. Is it possible to read the response headers, and status code? Or could you please expose them to public api please?
2. Is it possible to fetch binary data instead of string?  (e.g. download a file)

Thank you!

**Comment by lishid** [comment]
I will look into this a bit later, as it'll involve bridging native data for each platform we currently support.

**Comment by fyears** [comment]
Thanks. 

Maybe the best thing is that we have something like fetch or axios without cors limit, but I understand it might be too good to be true :-D . 

Or, maybe it’s possible to provide mobile-only api firstly? In desktop we have other options like using nodejs or electron api.  (It might introduce another issue that one plugin has to be built differently for desktop or mobile though)

**Comment by fyears** [comment]
Hi, happy new year!

May I ask is there any new solutions regarding this issue?

Thank you so much!

**Comment by lishid** [comment]
Happy new year! Apologies I have not been able to add this functionality yet.

**Comment by fyears** [comment]
Hi, what will be returned in `request()` string if the data is actually a binary file? I understand that further api changes need some development and some time, but is it possible to directly turn the current string "back" into its "original `ArrayBuffer`" if the data is binary? I tried `new TextEncoder().encode(res)` but no luck.

Similarly, is it possible to directly supply `ArrayBuffer` into `RequestParam#body`, though currently the api says its type being string? Or any workaround?

Thank you so much!

**Comment by lishid** [comment]
A new URL endpoint will be made available in an upcoming insider release called requestUrl which would return an object with status, headers and body as ArrayBuffer.

**Comment by fyears** [comment]
Cool! Thank you!

**Comment by lishid** [comment]
Yeah I will add that as well.
