### ISSUE TITLE
`onClick` doesn't respond to touch/tap event in mobile

### ISSUE THREAD

**Issue by fyears** [obsidianmd/obsidian-api#36]
I registered an [`HTMLElement#onclick`](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L169) event (on a `div`, not on a button), it works on desktop obsidian, but it doesn't work on mobile if I "tap" on mobile.

Is it an intentional design? Or is it possible to make it work on mobile, responding the equivalent touch/tap event?

**Comment by lishid** [comment]
Pretty sure it should work (it's just a `addEventListener('click')`). Mobile responds to click events normally.

**Comment by fyears** [comment]
Ok, I found out a more precise way to report the issue.

The click event indeed works. But there are some differences on mobile and desktop.

I wanted to list to "triple click", or "N-times-click-in-short-time". I found out [this](https://stackoverflow.com/questions/6480060/how-do-i-listen-for-triple-clicks-in-javascript), and use `event.detail` to capture how many clicks of the user.

On desktop it works as expected. But on mobile, even I clicked the area (`div` or any similar html element) multiple times very fast, `event.detail` always returns `1` instead of `N`.

Here is a sample plugin and the relevant sample code: https://github.com/fyears/obsidian-test-click/blob/master/main.ts#L29

Here are the screenshots. The first one is captured on desktop and the second on mobile.

![1](https://user-images.githubusercontent.com/1142836/143281999-656a53e2-3fff-4c5d-83a2-5b749da63102.png)
![2](https://user-images.githubusercontent.com/1142836/143282005-86f0bc78-693b-452f-abad-fcd2e4be81c6.jpg)

**Comment by fyears** [comment]
… And it was a ios safari bug, not an obsidian one.

The example on mdn website doesn’t work either: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

And one workaround is counting by using settimeout: https://stackoverflow.com/questions/55773096/how-to-detect-triple-click-on-website-on-ios-device


Since it’s not an obsidian api bug, I am closing this issue.

**Comment by lishid** [comment]
Ah yes, that does seem like an iOS specific behavior. Hope you find a way to work around it!
