### ISSUE TITLE
Can plugins add new file extension handlers?

### ISSUE THREAD

**Issue by sh-l** [obsidianmd/obsidian-api#39]
My use case is to link/open `.djvu` files in vaults.

Current status:
 - `.djvu` files do not show up in internal link suggestions (those shown while you are typing `[[` and some words)
 - Such internal links cannot be opened in a new pane. "Open in default app" works though.

To support above use cases, would it be possible for a plugin to declare that files with certain extensions should show up in link suggestions, and customize how such files would be rendered? For `.djvu`, it seems that [djvu.js](https://djvu.js.org/) is a possibility.

**Comment by lishid** [comment]
I'm assuming you're using the `registerExtensions` and `registerView` APIs to hook up your extension.

1. is a known issue, the link suggestion currently does not take into account dynamically registered ones yet.
2. I'm not too sure about.

**Comment by lishid** [comment]
These should be already addressed a while back.
