### ISSUE TITLE
Wrong API for MarkdownPostProcessor?

### ISSUE THREAD

**Issue by TilBlechschmidt** [obsidianmd/obsidian-api#4]
The API type definition requires the MarkdownPostProcessor to be a function which takes two arguments. However, when registering a simple plugin with such a post processor it causes exceptions:

```typescript
const postprocessor: MarkdownPostProcessor = (el: HTMLElement, ctx: MarkdownPostProcessorContext) => {
	console.log('post-processing!')
	console.log(ctx, el)
}

export default class MyPlugin extends Plugin {
	onload() {
		console.log('loading plugin');
		MarkdownPreviewRenderer.registerPostProcessor(postprocessor)
	}

	onunload() {
		MarkdownPreviewRenderer.unregisterPostProcessor(postprocessor)
		console.log('unloading plugin');
	}
}
```

![image](https://user-images.githubusercontent.com/5037967/99197565-a06b6280-2793-11eb-8e6e-e1c57585ae5c.png)

It apparently expects an object with a function called `render` which takes one argument. By inspecting the crashing code it looks like other PostProcessors that are registered take this shape where `e` seems to be the `HTMLElement`:

![image](https://user-images.githubusercontent.com/5037967/99197546-7a45c280-2793-11eb-84b1-91fb60f5861f.png)

Either the `registerPostProcessor` function fails to do a transformation of the value or the API definition is wrong, either way, it currently crashes on 0.9.11.

<sub>EDIT: I'm not quite sure if this is the place to report such an issue 🤷‍♂️</sub>

**Comment by TilBlechschmidt** [comment]
I just checked what would happen if I submit an object to the API which matches the other post processors by updating the API specification:

```typescript
/**
 * @public
 */
export type MarkdownPostProcessor = { render: (el: HTMLElement, ctx: MarkdownPostProcessorContext) => Promise<any> | void };
```

and subsequently updating the plugin code:

```typescript
const postprocessor = {
	render: (el: HTMLElement, ctx: MarkdownPostProcessorContext) => {
		console.log('post-processing!')
		console.log(ctx, el)
	}
}

export default class MyPlugin extends Plugin {
	onload() {
		console.log('loading plugin');
		MarkdownPreviewRenderer.registerPostProcessor(postprocessor)
	}

	onunload() {
		MarkdownPreviewRenderer.unregisterPostProcessor(postprocessor)
		console.log('unloading plugin');
	}
}
```

This seems to be working and calling the function with both the correct context and element.

**Comment by TilBlechschmidt** [comment]
A side question: The post-processor is called for each section of the document. Will it be called multiple times for the same document?

My intention here is to hide the first few sections (much like the new setting "hide frontmatter" does) of the preview. Attempting this with pure CSS yielded buggy results as I scrolled down the rendered document (my best guess is that it unmounts some HTML elements to optimise scrolling performance). Thus it is interesting to know if the post processor will only be called once in a burst to render the full document or if it can be called on sub-sections only.

**Comment by TilBlechschmidt** [comment]
![image](https://user-images.githubusercontent.com/5037967/99198393-9730c480-2798-11eb-906a-07dd59ef25b7.png)

It also seems like there is a number of additional properties on the `MarkdownPostProcessorContext` which are not specified in the API and thus can not be used without tricking TypeScript into allowing it. In my use case a number of these could come in very handy so I'd appreciate them being added 🙂

**Comment by lishid** [comment]
This API has been changed in a later version. That's why we added a minAppVersion https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/manifest.json#L5

**Comment by TilBlechschmidt** [comment]
Ah okay, that makes sense.

If you've got time to answer a quick question I'd appreciate it: I'm attempting to basically hide the first few lines of Markdown (up to the first `---` to be precise) in the preview. To give some context, a note might look like this:

```
**ID:** 20201106092415
**Type:** #📖 
**Status:** #🌱

**Topics:** [[Music]]
**Related:** [[SomeOtherTopic]]

---

Some note content!
```

In the HTML preview I'd like to hide the ID and reformat/aggregate the other fields into a single `<div>...</div>` which is nicely formatted (think of it as a status line at the top of the document).

Maybe I haven't understood the MarkdownPostProcessor fully yet but it seems to me that this is very hard to implement at the current time. Mostly because the processor is invoked on each section and (at least in my limited testing with version 0.9.11) there is no way to "escape" this section prison and gain access to other sibling HTMLElements.

With the fields themselves it wouldn't be so bad, I could theoretically remove the newline between them. However, this leaves the separator and I really do not want to get rid of that in the source file (it is used in other tools which parse this header and serves as a nice visual guide during editing).

Do you have any suggestions or pointers on how to approach this?

**Comment by lishid** [comment]
Hmm so the sections power a lot of internals and optimizations (stuff like measuring section heights for scroll-sync, removing sections that are not in view, highlighting sections when you click on search results or headings in the outline tab, etc.
That's why they aren't exposed, because there's too much magic going on that plugins could easily cause issues without having the full picture of how the internals work.

Can you explain a bit more what the end result would look like, regarding what would be hidden/removed, or reformatted?
Sounds like the only thing you're having trouble at this point is to find the right `<hr>` to hide, is that correct?

**Comment by TilBlechschmidt** [comment]
I kind of expected that to be the case (with the sections) 😄 

At the moment, I'm not quite sure on what the end result should be. As you can see from the example note, the header contains some status informations/metadata and references.

I've currently got two modes in mind:

1. Show a very slim bar which contains all the relevant information from the header (small font size, the type and status tags and links to the topics/related all in one row)
2. Completely hiding the first section

The first one would make the most sense when viewing a complete note. The latter is especially useful when looking at those little link-previews (as it is currently very cumbersome to scroll past the first 8 lines every time I hover a link).

At the moment, I'm running a selector on the section which looks if it starts with **ID:** or **Topics:** and if so, hides it. This works (although I'm not happy about having to run two selectors as some notes omit the Topics field and this prevents me from writing `**Topics:**` anywhere in the content) for solution 2 but misses the `<hr>`.

However, for solution 1 it fails because I can not access the metadata at once. It would probably require some very ugly HTML & CSS trickery to render the two subsequent sections in one row and leaves the problem of not being able to use `**Topics:**` in the body.

So yes, managing to uniquely identify and hide that `<hr>` would get me there and I could probably manage the remainder with some CSS trickery. I can't really inspect the popovers but it seems like they have a unique class, thus discerning between the two versions would work.

One thought that came to mind is using any sequence of random unicode characters which roughly resemble those `---` but are not parsed as a `<hr>` 🧐

**Comment by lishid** [comment]
😂 that's doable... But yeah I think you're fighting an uphill battle here with the current infrastructure.

I would think a bit in the future once we have frontmatter parsing done, you'd be able to convert all of this into proper frontmatter and use plugins to display the contents as a header of the document. That's going to take some time to get to though

**Comment by TilBlechschmidt** [comment]
Okay, so I'll reside to quirky CSS hacks for now and wait for the frontmatter to be "feature-complete" then 😄 

Speaking of frontmatter, I noticed that tags and references are currently not parsed in there. Is there or will there be a way to handle this?

If so, it would make this the perfect location for such types of metadata (and simplify parsing in other tools).

**Comment by lishid** [comment]
We might parse them from the engine, but if not, plugins will have APIs later to access those fields so they can parse them however they want.

**Comment by TilBlechschmidt** [comment]
Well then, thank you for your quick and in-depth response! Really appreciate it 😊

I'll definitely go and buy Catalyst soon! You guys are killing it with not only the application itself but also in how you handle your community 👍

<sub>Plus I'm already way down the PKB rabbit hole 🤷 </sub>

**Comment by lishid** [comment]
Enjoy the ride!
