### ISSUE TITLE
Allow returning promise in SuggestModal's getSuggestions

### ISSUE THREAD

**Issue by MunGell** [obsidianmd/obsidian-api#41]
Hi,

This is API feature request.

At the moment [`SuggestModal`'s](https://github.com/obsidianmd/obsidian-api/blob/342a49dcc4e2012e4c60e16a5a3d16d740ad86b6/obsidian.d.ts#L2954) implementation of [`getSuggestions`](https://github.com/obsidianmd/obsidian-api/blob/342a49dcc4e2012e4c60e16a5a3d16d740ad86b6/obsidian.d.ts#L2996) allows only array returns (`T[]`).

This limits its use to only static suggestions (i.e. selection from a predefined number of commands).

I am working on a plugin that needs to be able to receive suggestions from an HTTP endpoint. In order to achieve this `getSuggestions` needs to also allow `Promise<T[]>` returns.

[`EditorSuggest`'s](https://github.com/obsidianmd/obsidian-api/blob/342a49dcc4e2012e4c60e16a5a3d16d740ad86b6/obsidian.d.ts#L882) implementation of [`getSuggestions`](https://github.com/obsidianmd/obsidian-api/blob/342a49dcc4e2012e4c60e16a5a3d16d740ad86b6/obsidian.d.ts#L916) already has this functionality.

Please let me know if more information is required

Thanks a million!

**Comment by kometenstaub** [comment]
That should be implemented as of 0.13.26

https://github.com/obsidianmd/obsidian-api/blame/c01fc3074deeb3dfc6ee02546d113b448735b294/obsidian.d.ts#L3034
