### ISSUE TITLE
Value rename events return `TFile` and not `TAbstractFile`

### ISSUE THREAD

**Issue by coltoneshaw** [obsidianmd/obsidian-api#42]
https://github.com/obsidianmd/obsidian-api/blob/342a49dcc4e2012e4c60e16a5a3d16d740ad86b6/obsidian.d.ts#L3366

I've noticed a large number of events returning the whole `TFile` instead of `TAbstractFile` as it's listed in the types here. The above and it also seems to happen on `file-menu` events.

**Comment by lishid** [comment]
Not sure I understand what you're asking. `TFile` inherits `TAbstractFile`. The other possible type is `TFolder` which also inherits `TAbstractFile`.

**Comment by lishid** [comment]
It is possible to rename a folder, in which case you will get a TFolder instead.

You need to test for `file instanceof TFile` before proceeding with using things like `basename`.

**Comment by coltoneshaw** [comment]
@lishid - Maybe i'm missing something but the return types are not defined here correctly in my opinion. Taking the below rename event:

```typescript
on(name: 'rename', callback: (file: TAbstractFile, oldPath: string) => any, ctx?: any): EventRef;
```

I don't see how one would know that it emits both a `TFile` and a `TFolder` response. Wouldn't it be more clear to rewrite these events with all the possible returns, then the dev can do `instanceof` to handle each type?

Like below:

```
on(name: 'rename', callback: (file: TFile | TFolder, oldPath: string) => any, ctx?: any): EventRef;
```

**Comment by lishid** [comment]
That's a good suggestion, I will think about it!

**Comment by coltoneshaw** [comment]
Thank you. It would remove a ton of the guesswork on what's returned on some of these events. 

I'm finding myself having to trigger the event, see the response, and then find the actual type that's returned. 

I'm happy to open a PR for these, I'm just unsure if I'm missing any possible responses. Like on this rename event I can only guess what's returned based on what I can test/see.
