### ISSUE TITLE
is it possible to expose Stat for TFolder?

### ISSUE THREAD

**Issue by fyears** [obsidianmd/obsidian-api#43]
Hi,

Currently a Stat property containing mtime and ctime is exposed for TFile, but the same info is not exposed for TFolder. It is possible to directly include this info insider TFolder? 

Thanks!

**Comment by fyears** [comment]
… and adaptor.stat(any_folder) also returns 0 mtime and ctime, is it possible to “fix” this as well? (if not intentionally designed)

Thank you so much!

**Comment by lishid** [comment]
For stat, we currently intentionally return 0 for both but I guess it wouldn't hurt to return whatever the underlying OS gives us. Will ship this next patch.

For the actual stat property, I will look into this later as it's slightly more involved in the underlying code changes required to expose this.

**Comment by lishid** [comment]
I think we'll leave it as it is for now - you can use stat() to get it, but it won't be available on the TFolder object.
