### ISSUE TITLE
Is there API Documentation?

### ISSUE THREAD

**Issue by phillipjohnston** [obsidianmd/obsidian-api#44]
Is there API documentation somewhere that indicates how these interfaces are to be used?

**Comment by phillipjohnston** [comment]
For example... what exactly is the offset here?

```
export interface Loc {
    /**
     * @public
     */
    line: number;
    /**
     * @public
     */
    col: number;
    /**
     * @public
     */
    offset: number;
}
```

**Comment by lishid** [comment]
A lot of it doesn't have explanations yet, but if you head over to the discord server there's a `#plugin-dev` channel where other plugin devs can help you.

There's also some docs here that may help: https://marcus.se.net/obsidian-plugin-docs/

**Comment by dredhorse** [comment]
any idea what the official roadmap for the API is? atm it is quite underwhelming 
I think that obsidian will thrive because of plugins, making it hard to code / maintain plugins will lead to the opposite.
Especially as a lot of major plugins are looking like they have been abandoned already.

**Comment by LightTemplar** [comment]
There is now official doc: https://docs.obsidian.md/
