### ISSUE TITLE
are some restrictions of `requestUrl` expected?

### ISSUE THREAD

**Issue by fyears** [obsidianmd/obsidian-api#46]
Hi,

I just have the opportunity to try the new `requestUrl`, but I find something weird restrictions:

The `headers: {}` cannot content the following keys: `host`, `content-length`

try this:

```js
  requestUrl({
    url: "https://httpbin.org/put",
    method: 'PUT',
    headers: {
        x: 'x',
        'content-length': '331'  // comment or not comment
    },
    body: 'xyz'
  }).then(x=>console.log(x.json))
```

Here is the error: 
```
index.html:1 Uncaught (in promise) Error: net::ERR_INVALID_ARGUMENT
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7068)
    at SimpleURLLoaderWrapper.emit (node:events:394:28)
Promise.then (async)
(anonymous) @ VM587:9
```

![04d1bfebca1cf64cbdb047089e91456](https://user-images.githubusercontent.com/1142836/157281095-7112e010-fb53-4322-a438-ae87fc0b6c18.png)

I don't know it's by designed or not, and I can only find out the above headers by try and error. Are there any more docs here?

**Comment by fyears** [comment]
... and may I ask how to debug the network call by `requestUrl`? The network in dev tools is not working by this method.

**Comment by lishid** [comment]
Yeah you aren't allowed to set either because Content-Length is determined by the actual length of the body you give, and host is parsed from the URL. I don't know a better way to debug this network call since it uses Electron's internal net package and not the chromium browser's page.

**Comment by fyears** [comment]
Ok. 

So no other disallowed header keys?

And maybe you could change the signature using omit indicating host and content-lenght not being allowed? Some example like https://stackoverflow.com/questions/58594051/typescript-object-with-any-keys-except-one

**Comment by lishid** [comment]
The underlying APIs didn't have anything about this so I'll just leave it like that for now. I'm only guessing why those don't work, but if one understands what HTTP does, I think it's pretty reasonable why you can't/aren't supposed to manually set those headers.

I don't know if there's other disallowed keys. They are also platform dependent (maybe on mobile they are ignored instead of throwing an error).

**Comment by fyears** [comment]
According to the hints above, I found out the list of disallowed headers due to the design of Electron `net`: https://www.electronjs.org/docs/latest/api/client-request#instance-methods

**Comment by lishid** [comment]
Great find!
