### ISSUE TITLE
setActiveLeaf doesn't remove current focus if target view doesn't handle `focus` state

### ISSUE THREAD

**Issue by pjeby** [obsidianmd/obsidian-api#47]
If you attempt to activate and focus a leaf via the API, and the targeted leaf's view doesn't explicitly handle the `focus` ephemeral state (e.g. backlinks view, outline view, graph view, empty pane, etc.), focus remains wherever it was before.  In order to get this to work properly, one has to also explicitly blur the previously-focused element, otherwise commands and cursor movement may affect the previously-active pane.

Perhaps WorkspaceLeaf's `setEphemeralState()` with a `.focus` should blur the active element if it's not a child of the leaf, before calling the view's setEphemeralState? That way, if the view actually does manage its own focus, it won't be affected by redundantly setting the state, but the many types of views in the core and third-party plugins wouldn't have to duplicate this functionality if they don't need a specific element to be focused.

**Comment by lishid** [comment]
Will be included in v0.14.3!
