### ISSUE TITLE
`requestUrl` turns all headers keys to lower cases on PC but preserve the cases on mobile

### ISSUE THREAD

**Issue by fyears** [obsidianmd/obsidian-api#54]
```js
requestUrl({url: 'https://httpbin.org/response-headers?SOMETHING=anything'}).then(x=>{
    console.log(x.headers)
})
```

It outputs these on windows Obsidian:

```
something: "anything"
...
```

But it outputs these on Android (and iOS?) Obsidian:

```
SOMETHING: "anything"
...
```

Pay attention that the key `SOMETHING` was turned into `something` on Windows.

Although headers keys should be case-insensitive, but the above inconsistency did introduce a bug into my plugin and costed some time to find out. Maybe it's better to make the keys "all preserving cases" or "all using lower cases" across platforms?

**Comment by lishid** [comment]
Headers are sent and received from the underlying native APIs directly, we don't touch it.

According to Electron's documentation [here](https://www.electronjs.org/docs/latest/api/incoming-message#responseheaders):

> All header names are lowercased.

There is not much we can do to un-lowercase it.

**Comment by lishid** [comment]
Perhaps you should file a feature request to Electron instead.
