### ISSUE TITLE
Incomplete Support for CodeMirror commands

### ISSUE THREAD

**Issue by PeteMichaud** [obsidianmd/obsidian-api#60]
Not sure this is the right repo for this report, please let me know if I should move it!

I'm currently trying to update the Text Snippet plugin, and noticed that the `EditorCommandName` type at https://github.com/obsidianmd/obsidian-api/blob/036708710c4a4b652d8166c5929d5ba1ffb7fb91/obsidian.d.ts#L856

doesn't support all the commands that CodeMirror supports. In particular I need to use `goLeftWord` but I can't. The current version of the plugin directly uses instances of the CodeMirror editor object, and I'm trying to move it over to the Obsidian Editor abstraction, but this is a blocker.

**Comment by lishid** [comment]
We can look into supporting that in the next version. `Editor` is an abstraction between CM5 and CM6 and thus we have to implement the proper proxying for both sides.

**Comment by lishid** [comment]
I will add `goWordLeft` and `goWordRight` in v0.14.7.
