### ISSUE TITLE
Possibility to expose Vim instance for monkey-patches?

### ISSUE THREAD

**Issue by aidenlx** [obsidianmd/obsidian-api#65]
I have received feature request from users who [want to allow Chinese word splitting to work in vim mode](https://github.com/aidenlx/cm-chs-patch/issues/4). After checking the source code of codemirror-vim, it seems that it's using [a private method](https://github.com/replit/codemirror-vim/blob/a2d37a01f68ee21a041f72c7272b3b4f9471cf7d/src/vim.js#L3635) to detect words instead of `findWordAt` in cm5 or `wordAt` in cm6. It should be able to be monkey-patched similar to how Chinese word splitting has been implemented in cm5, but it seems like [the vim instance](https://github.com/replit/codemirror-vim/blob/a2d37a01f68ee21a041f72c7272b3b4f9471cf7d/src/index.ts#L8) is not exposed to plugins. So I'm wondering if it's possible to access the vim instance?

**Comment by lishid** [comment]
You can access the cm6 vim mode through `window.CodeMirrorAdapter.Vim`.

**Comment by aidenlx** [comment]
Thanks!
