### ISSUE TITLE
Insider version (v0.14.12) not support drag and drop event

### ISSUE THREAD

**Issue by MarkMindCkm** [obsidianmd/obsidian-api#68]
When test the drag event  in v0.14.12 , the drop event is not triggered，v0.14.6 is  normal

https://github.com/MarkMindCkm/obsidian-markmind/issues/340

https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/issues/83

the code is like this

``` js
function appDrop(evt){
   console.log(evt)
}

dom.addEventListener('drop', appDrop);

```

the `dragstart/dragend`  is support

**Comment by lishid** [comment]
I've investigated this and the only difference I'm seeing is in v0.14.8 where we changed the order of operations on `dragover` where it will always set the `evt.dataTransfer.dropEffect` to `none` in a capture mode handler.

I think it should work if you set it to something else in your `dragover` event handler, in addition to calling `preventDefault`.

I can also add a fix where default prevented events would have it set back to the original value

**Comment by lishid** [comment]
Did you get a chance to see if `dropEffect` could indeed fix your issue?

**Comment by MarkMindCkm** [comment]
> Did you get a chance to see if `dropEffect` could indeed fix your issue?

I have test this :

``` js
  if(evt.dataTransfer){
            evt.dataTransfer.effectAllowed = 'all' // or move
            evt.dataTransfer.dropEffect = 'all'; //or move
 }

```

but it is not work

**Comment by lishid** [comment]
Ok well whatever I did fixed the issue with Kanban so it probably fixed it for yours as well. Let me know once we deploy the new insider next week and if all goes well we can close the issue then.

**Comment by MarkMindCkm** [comment]
> Ok well whatever I did fixed the issue with Kanban so it probably fixed it for yours as well. Let me know once we deploy the new insider next week and if all goes well we can close the issue then.

0.14.13 work fine , thanks
