### ISSUE TITLE
Provide an event for when the editor re-renders due to Live Preview

### ISSUE THREAD

**Issue by faurehu** [obsidianmd/obsidian-api#69]
I have developed a plugin that appends a class name to links when the file opens. Unfortunately, the editor re-renders when using Live Preview and these classes are not reloaded on the links. Is there an event I can listen to rewrite these classes on re-render? Or is there a way to permanently write in class names in these link elements?

Thank you.

**Comment by lishid** [comment]
You are not allowed to arbitrarily modify DOM elements in the editor as it will automatically revert any changes. For that you should create a CodeMirror 6 extension to provide decorations.

Lastly, please head to the discord server under the `#plugin-dev` channel for help with using the API. Issues in this repo is meant for actual bugs with the API, not questions. It's also not watched by other plugin developers, and as such you won't receive as much help.
