### ISSUE TITLE
Bug: EditorSuggest class no member of the obsidian module

### ISSUE THREAD

**Issue by mikebarkmin** [obsidianmd/obsidian-api#78]
**Steps to reproduce:**

- Install obsidian-excalidraw on Android.
- Try to activate it.

**Bug:**

This will produce an error:

Can not extend undefined. This happens when a class is extended from obisidan.EditorSuggest. I looked at the module obsidian in the debugger, and it does not have a EditorSuggest property.

**Comment by lishid** [comment]
I tried this on Android and I am unable to reproduce. The plugin works just fine and I did not receive any errors. 

I've also double-checked that `EditorSuggest` is indeed exported correctly, so most likely whatever you're doing isn't importing `obsidian` correctly and EditorSuggest happened to be the first one you try to actually use.

**Comment by mikebarkmin** [comment]
I am just using the app and installed the obsidian-excalidraw plugin.

**Comment by mikebarkmin** [comment]
After deinstalling and installing Obsidian from the PlayStore again everything works.
