### ISSUE TITLE
Ability to disable Settings

### ISSUE THREAD

**Issue by jjspace** [obsidianmd/obsidian-api#8]
It would be great to be able to disable specific settings. For example if two toggle settings are "linked" so that the second only applies if the first is enabled. It would be great to be able to show both settings so the user understands that they both exist but have the second disabled (visually and functionally) so they can't click it without enabling the other one first.

I'm picturing something like this:
```js
// ... in display() of PluginSettings
const setting1 = new Setting(containerEl)
  .setName('First setting')
  .setDescription('enable something and allow second setting to be set')
  .addToggle((toggle) => toggle.setValue(this.plugin.settings.firstOpt).onChange(async(value) => {
    this.plugin.settings.firstOpt = value
    await this.plugin.saveSettings();
    if (value) {
      setting2.enable()
    }
    else {
      this.plugin.settings.secondOpt = false;
      setting2.disable()
    }
  }))

const setting2 = new Setting(containerEl)
  .setName('Second setting')
  .setDescription('Enable something else. only enabled when firstOpt is on')
  .addToggle((toggle) => toggle.setValue(this.plugin.settings.secondOpt).onChange(async(value) => {
    this.plugin.settings.secondOpt = value;
    await this.plugin.saveSettings();
  }))
if (this.Plugin.settings.firstOpt) {
  setting2.disable()
}
```

**Comment by lishid** [comment]
I think I understand your use case, for now you'll have to manually disable the control elements, and possibly add some styles to the entire line to be more explicit.

One thing I'd like to note is that `Setting` don't keep track of its internal controls at the moment, which makes it a bit more difficult. Right now, we don't currently have such a need yet, but when we do it won't be too hard to add.

**Comment by jjspace** [comment]
> you'll have to manually disable the control elements

That's kinda what I ended up doing. However because of the way inputs are set up (the toggle specifically) there is no way to actually disable, remove or block the click handler. The best I could come up with is adding the css: `pointer-events: none;`. As a web dev myself this is a terrible way to disable an input, if it's the only one implemented, which is why I created the request for an internal option.

Hopefully we can get something like this in the future!

**Comment by lishid** [comment]
Ah I see what you mean. That's definitely a problem.

**Comment by lishid** [comment]
`setDisabled` is now available on Setting and Component. I totally forgot to comment here but it's been in for a few releases already.

**Comment by jjspace** [comment]
@lishid Oh awesome! Thanks for adding that!
