### ISSUE TITLE
repository does not have a LICENSE file

### ISSUE THREAD

**Issue by joshua-mcintosh** [obsidianmd/obsidian-api#82]
I noticed this repo did not have a LICENSE file, though [the NPM page](https://www.npmjs.com/package/obsidian) notes the package is MIT licensed. it would be useful to document this directly in the history of the repository by adding a LICENSE file, as this makes licensing obvious to contributors and users alike, and helps track the history on terms of use should the license change in the future.

(This is not strictly an API bug, so feel free to migrate the request elsewhere or ask me to do the same; I ask that you link to the new request if created.)

**Comment by lishid** [comment]
Fixed.
