### ISSUE TITLE
Add a function to get file by yaml  attribute value

### ISSUE THREAD

**Issue by MarkMindCkm** [obsidianmd/obsidian-api#83]
if add yaml to a md file :

```
---
id: 12345
---
```

please add a api for example `app.getFileByYaml({id:12345})` to get this md file

**Comment by lishid** [comment]
You can do it directly by going through all files and querying metadata cache for the frontmatter. If you need to do this often, I'd recommend creating an index in your plugin.

Unfortunately it doesn't make sense for Obsidian to create an index for this because not everyone uses "id" for querying.
