### ISSUE TITLE
Feature Request: add  `registerSelectionSuggest` similar to `Plugin_2#registerSelectionSuggest`.

### ISSUE THREAD

**Issue by madroidmaq** [obsidianmd/obsidian-api#86]
It is recommended to increase the registration callback of selection, when the user selects the content, it can provide some suggestions or option operations appropriately. Actions similar to those suggested in the Notion below:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/6247142/200175489-8714effc-76f5-4ee3-817c-96134f9697f6.png">

The interface function I understand is roughly similar to `Plugin_2#registerEditorSuggest`, the trigger condition of `Plugin_2#registerEditorSuggest` is while the user is typing.

The name of the interface is similar to `Plugin_2#registerSelectionSuggest` 。

**Comment by liamcain** [comment]
Hi, this isn't really the best place for feature requests. Instead, feature requests should be submitted to [the forum](https://forum.obsidian.md/c/feature-requests/8) if there isn't already a request for this.

Also, for this particular feature request, I think there are actually a couple plugins that provide this feature (see https://github.com/cumany/obsidian-editing-toolbar or the beta plugin Make.md (<https://discord.com/channels/686053708261228577/707816848615407697/1037573705917808716>).
