### ISSUE TITLE
Document that request and requestUrl send the request body in base64

### ISSUE THREAD

**Issue by swar8080** [obsidianmd/obsidian-api#89]
The following code is unexpectedly sending the request body in base64 encoding:

```
import { request } from 'obsidian';

 const res: string = await request({
        url: BACKEND_API_URL,
        method: 'POST',
        body: JSON.stringify(newPluginVersionRequest),
    });
```

It would be helpful to document this in the typescript definition since people will expect the body to be sent as is.

Also, on android mobile the `method` must be uppercase (ex: GET, POST, etc.)/. Using `"post"` surfaced what seems like a java error: `ProtocolException method does not support a request body post`.

---
I'm assuming I can't submit a PR for this documentation change since `obsidian.d.ts` is likely generated by your private code repository?

**Comment by lishid** [comment]
That might be a bug - what platform is it?

**Comment by swar8080** [comment]
My mistake, AWS API gateway is base64 encoding the body after I switched from using `fetch` to `request` (https://aws.amazon.com/blogs/compute/handling-binary-data-using-amazon-api-gateway-http-apis/)
