### ISSUE TITLE
Expose original link text for aliased links in DOM

### ISSUE THREAD

**Issue by sh-l** [obsidianmd/obsidian-api#92]
I'd like to hook into click events on internal links. Currently, I'm attaching a `click` event handler on `document`, and inside the event handler, I read off the event's target's `textContent` to get the link's target, then calls `getFirstLinkpathDest`. On internal links with an alias like `[[real_path.md|alias]]`, there's no hint of `real_path.md` in DOM, so I cannot read off the link's real target.

It would be nice if this use-case can be supported either by exposing real targets in DOM, for example by some attributes, or via a dedicated API that allows plugin to hook into click events on internal links.

**Comment by lishid** [comment]
This isn't a use case we can support. You don't even know the source path of the file when doing that and so you won't be able to resolve relative links properly.
