### ISSUE TITLE
Canvas strings use seemingly invalid newlines

### ISSUE THREAD

**Issue by dzuk-mutant** [obsidianmd/obsidian-api#93]
I know this isn't strictly in the API code but it pertains to the usability of Obsidian Canvases outside of Obsidian nonetheless. (I hope this is an appropriate place to put such an issue)

I was making a package for parsing and using Obsidian Canvases in the Elm programming language and I found that when I try to parse a .canvas file made by Obsidian, various JSON parsers (including the parser I was using in Elm) don't like single escaped newlines (`\n`) because they interpret them as a literal newline in the file itself and not a newline inside the string the newline is places in. For newlines inside a JSON string, double-escaped (`\\n`) is the expected way of doing things.

Example error in Elm with a JSON that comes direct from Obsidian:
(parsing works once I manually replace all instances of `\n` with `\\n` inside JSON strings)
``` 
Err (Failure ("This is not valid JSON! Unexpected token \n in JSON at position 130") <internals>)
```

Example in the Firefox console:
```
> JSON.parse('{"foo":"bar\\n"}')
> Object { foo: "bar\n" }

> JSON.parse('{"foo":"bar\n"}')
> Uncaught SyntaxError: JSON.parse: bad control character in string literal at line 1 column 12 of the JSON data
    <anonymous> debugger eval code:1
```

**Comment by lishid** [comment]
> various JSON parsers (including the parser I was using in Elm) don't like single escaped newlines (\n) because they interpret them as a literal newline in the file itself

I don't believe this - if you write `"\\n"` then it will be interpreted as literally a backslash character + `n`. JSON is a well documented standard so it is easy to verify whether Obsidian's JSON is compliant or not. Simply plug the data file into any online validator like https://jsonlint.com/ and you should be able to see if Obsidian's JSON is valid or not.

If you have a raw canvas file that is not JSON compliant, send it here and I can take a look. If a JSON compliant canvas file fails to open in whatever other language you're using then you should file a bug report with the language instead.

Lastly, this section is for bug reports with the Obsidian API. For other issues with Obsidian in general you should report to the forum.
