### ISSUE TITLE
Bug: EditorSuggest.onTrigger forward nullable `file` in canvas node editor

### ISSUE THREAD

**Issue by aidenlx** [obsidianmd/obsidian-api#94]
https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L1062

it seems that the `updateEvent()` function forward `editor` and `file` of`MarkdownFileInfo` to `onTrigger` function, in which `file` can be null. 
<img width="1221" alt="CleanShot 2023-01-22 at 16 52 41@2x" src="https://user-images.githubusercontent.com/31102694/213907738-8dd6f689-a88e-491b-89b4-7937a7bc1ceb.png">

**Comment by lishid** [comment]
Thanks, I will change file to be `TFile | null`.

**Comment by aidenlx** [comment]
fixed in v1.1.13 API, closing it
