### ISSUE TITLE
Bug: `vault.rename` not updating file links

### ISSUE THREAD

**Issue by ramarivera** [obsidianmd/obsidian-api#95]
**Steps to reproduce:**
- Create two notes, A and B
- Create a link `[[B]]` in A
- Run `vault.rename` on file B, and rename it to C
- The link to B on A is still there, but is invalid.

I am filing this as a bug report mostly because doing Right Click -> Rename on a file, seems to properly update links, so it seems at least like inconsistent behavior

**Comment by liamcain** [comment]
You should be using [`renameFile`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L1215) if you want the links to update properly. Not vault.rename.

**Comment by ramarivera** [comment]
Thanks for pointing that out!
