### ISSUE TITLE
Request: Include all Lucide icons

### ISSUE THREAD

**Issue by scottwillmoore** [obsidianmd/obsidian-api#96]
I don't know if this should be classed as a bug, but it appears that some Lucide icons are not packaged with Obsidian.

For example, there is no `heading`, `heading-1`, `heading-2`, ... and no `ear`, `ear-off`. I expect there are more that are not included.

Would it be possible to add these to Obsidian? Is there a reason they have not been bundled?

Also, the `addIcon` is weird, as it doesn't allow you to control the SVG element, and hence you cannot adjust attributes such as `width`, `height`, `viewbox`, `stroke-width`, etc. For example, `viewBox` is forced to be `0 0 100 100`. Therefore, it is not possible to easily add more Lucide icons from within a plugin, without adjustment. In addition, the SVG attributes returned from `getIcon` while be different for built-in Lucide icons, as opposed to icons that have been added.

**Comment by lishid** [comment]
You're probably looking at a newer version of Lucide than what is included in Obsidian - we update the library from time to time, but what you get in the wild is almost always lagging behind by a few months.

Will update it again for one of the next releases though.

**Comment by Hunanbean-Collective** [comment]
> You're probably looking at a newer version of Lucide than what is included in Obsidian - we update the library from time to time, but what you get in the wild is almost always lagging behind by a few months.
> 
> Will update it again for one of the next releases though.

I think there is a more severe issue. No icons at all seem to work for a custom callout.

```css
.callout[data-callout="idea"] {
    --callout-color: 255, 255, 0;
    --callout-icon: lucide-alert-circle;
}
```
that is a simple variation on the documentations example from here:
[https://help.obsidian.md/Editing+and+formatting/Callouts#Customize%20callouts](https://help.obsidian.md/Editing+and+formatting/Callouts#Customize%20callouts)

this does not work. Please ensure that things are functioning properly, or if there have been syntax changes, reflect them in the documentation.

Thank you 

p.s. i will open a new issue if needed

**Comment by lishid** [comment]
Works for me.
![image](https://github.com/obsidianmd/obsidian-api/assets/609710/3da75506-a048-4648-990a-c547354698db)

**Comment by Hunanbean-Collective** [comment]
ok. it requires a close and reload of Obsidian here (perhaps a toggle off first). that has bitten me before, but is workable.

thanks
