### ISSUE TITLE
Request: enable cross origin isolation for `app://obsidian.md` in electron app

### ISSUE THREAD

**Issue by aidenlx** [obsidianmd/obsidian-api#97]
## Problem

Obsidian desktop app currently lacks cross-origin isolation support for the location `app://obsidian.md`, which limits its ability to integrate with projects that require `SharedArrayBuffer`, such as ffmpeg-wasm and sqlite3-wasm.

## Possible Solution

The following sample code can be used to enable `SharedArrayBuffer` and add the necessary CORS headers, by using the `webRequest` API (source: https://stackoverflow.com/questions/71770369/use-sharearraybuffer-from-an-electron-app). Enabling this on mobile [seems to be impossible for now](https://github.com/ionic-team/capacitor/discussions/5502)

```js
browserWindow = new BrowserWindow({...});

// Enable SharedArrayBuffer
browserWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    if (new URL(details.url).origin === 'app://obsidian.md') {
        details.responseHeaders['Cross-Origin-Opener-Policy'] = ['same-origin'];
        details.responseHeaders['Cross-Origin-Embedder-Policy'] = ['require-corp'];
    }
    callback({ responseHeaders: details.responseHeaders });
});
```

> **Note**
> this feature may impact loading other cross-origin resources. 
> Here is a detailed guide on enabling cross origin isolation, which include analyzing the impact of cross-origin isolation on existing resources: https://web.dev/cross-origin-isolation-guide/

**Comment by lishid** [comment]
We actually forcibly enable SharedArrayBuffer for electron using the other suggestion from the SO post you sent

```js
app.commandLine.appendSwitch('enable-features','SharedArrayBuffer')
```

Is that not working for you?

**Comment by lishid** [comment]
![image](https://user-images.githubusercontent.com/609710/218104493-62695c7e-2a98-4fbd-8c2a-6bc0ef971827.png)

**Comment by aidenlx** [comment]
oh i thought this flag no longer work since chrome 92... maybe there is some issues around the feature detection that use window.crossOriginIsolated
