### ISSUE TITLE
app.commands forcing typescript error check

### ISSUE THREAD

**Issue by qaptoR** [obsidianmd/obsidian-api#99]
**Steps to reproduce:**
- developing a normal plugin in VS Code

When trying to refer to `this.app.commands` a typescript error is shown.

![image](https://user-images.githubusercontent.com/40372043/219991236-b0afb584-35c9-4de2-820d-c7bf4e8547d3.png)

![image](https://user-images.githubusercontent.com/40372043/219991274-a5508193-0f34-411c-a878-b6ab405fb881.png)

From what I can guess, this is because `app.commands` is not intended to be a part of the API, even though it can be run in the console, and is still accessible in typescript.

Whatever the reason though I believe that if it IS accessible it should be documented, and it should be visible.

The reason is simple: otherwise it's considered deep magic. You can only do it if you can discover you can do it with the proper research, which isn't fair to any developer.

ie. if the reason is to discourage plugin developers from having dependencies on other plugins, that should not be up to the API to decide. Maybe community plugins shouldn't have such dependencies, but personal use plugins should very much encourage the automatic use of plugin commands.

and so it follows that if there is any other deep magic obsidian can do that is not exposed, it should be.

**Comment by lishid** [comment]
You can access pretty much anything inside Obsidian's internals but that doesn't mean we want to add it to the typescript documentation for everyone to use. The documented APIs are intended for long-term support and we usually don't make changes to them without significant effort for backward compatibility, whereas private APIs are not intended for public use and are subject to change anytime.
